name: Bug report
description: Report a reproducible defect
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened and what did you expect?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: Provide exact commands and inputs.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version / commit
      description: Tag or commit hash
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste error logs or stack trace
      render: shell
